### PR TITLE
[IT-255] Synapse External bucket PR example

### PR DESCRIPTION
**Pull request by zaro0508**
This is an example PR (do not merge!).  It is a template to show
how to get the CI system to automatically provision a Synapse External
bucket.

Bucket creation workflow:
  1. Scientist create a PR similar to this one.  Create a new file
     with a unique stack_name and updated parameters.
  2. Have someone review and approve the PR.
  3. Merge the PR
  4. The CI system will auto provision the bucket
  5. An email will be sent to the bucket owner email address with
     the new bucket info.

The newly created bucket will contain the following tags:

 ```
key: aws:cloudformation:stack-id
 value: arn:aws:cloudformation:us-east-1:<AWS account ID>:stack/GatesKI-TestStudy/375ced80-78b9-11e8-bc55-500c286e1a36

 key: aws:cloudformation:stack-name
 value: GatesKI-TestStudy

 key: aws:cloudformation:logical-id
 value: SynapseExternalBucket

 key: OwnerEmail
 value: joe.smith@sagebase.org
```

To remove the bucket
1. Bucket owner creates a new PR that deletes the files that was added by
    the PR that was used to add the bucket.  
2. Have an an AWS account Admin review your change.
3. Approve and merge.

Since cloudformation does not allow deleting a buckets with data in it
the bucket owner will need to contact an admin to delete the bucket
on their behalf.

### CODE REVIEW

**Comment by kdaily** [comment]
What is a unique stack name? Is this what I want my bucket to be called?

**Comment by zaro0508** [comment]
No, That is the cloudformation stack name.  We want CF to manage the bucket names because there are a bunch of limitations[1] that could cause the process to fail.  For example bucket names must be unique across all existing bucket names in Amazon S3.  CF will create the bucket and gives it a globally unique name and that bucket name will be sent to the bucket owner in the an email.

[1] https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by kdaily** [comment]
Got it! Sorry I should have read the file contents submitted with this PR. It's clear. LMK when #74 is in and I'll test this out.

**Comment by zaro0508** [comment]
When CF creates the bucket it will automatically set the following tags:

key: aws:cloudformation:stack-id
value: arn:aws:cloudformation:us-east-1:055273631518:stack/GatesKI-TestStudy/375ced80-78b9-11e8-bc55-500c286e1a36

key: aws:cloudformation:stack-name
value: GatesKI-TestStudy 

key: aws:cloudformation:logical-id
value: SynapseExternalBucket

**Comment by zaro0508** [comment]
This service has been moved to Sage-Bionetworks/scicomp-provisioner example PR over there is at https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/4

**Pull request closed without merging**
